name:  FSC (Usuarios Finales)
description: Solicitud de cambio simplificada para usuarios finales y dise帽adores.
title: "[FSC-Usuario]: "
labels: ["FSC-UsuarioFinal", "1 - Pendiente Revisi贸n"]

body:
  - type: markdown
    attributes:
      value: |
        **Proyecto:** CursosUniversidad
        *(El N掳 de Cambio se asignar谩 autom谩ticamente al crear la solicitud).*
        
        ---
        ## Secci贸n 1: Informaci贸n General y Justificaci贸n

  - type: input
    id: solicitado-por
    attributes:
      label: Solicitado por (Nombre y Rol)
      placeholder: "Ej: Ana P茅rez (Dise帽adora UX)"
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: Informaci贸n de Contacto (Correo Electr贸nico)
    validations:
      required: false

  - type: input
    id: telefono
    attributes:
      label: Informaci贸n de Contacto (Tel茅fono)
    validations:
      required: false

  - type: input
    id: fecha-solicitud
    attributes:
      label: Fecha de Solicitud
      description: "Puedes usar el formato AAAA-MM-DD"
      placeholder: "Ej: 2025-10-30"
    validations:
      required: true

  - type: textarea
    id: descripcion-cambio
    attributes:
      label: Descripci贸n Detallada del Cambio
    validations:
      required: true

  - type: textarea
    id: motivo-cambio
    attributes:
      label: Motivo y Justificaci贸n del Cambio
    validations:
      required: true

  - type: dropdown
    id: tipo-cambio
    attributes:
      label: Naturaleza del Cambio
      options:
        - Nuevo Requerimiento
        - Cambio a Requisito Existente
        - Defecto/Error
    validations:
      required: true

  - type: dropdown
    id: prioridad
    attributes:
      label: Prioridad Solicitada
      options:
        - 1 - Alta
        - 2 - Media
        - 3 - Baja
    validations:
      required: true